# Generated by Django 3.0.2 on 2020-02-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_auto_20200203_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name']},
        ),
    ]
